name: Build macOS app

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-macos-app:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Upgrade pip and install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install py2app pyobjc pygame

      - name: Build app with py2app
        run: |
          python setup.py py2app

      - name: Show build output files
        run: ls -l dist/

      - name: Upload .app artifact
        uses: actions/upload-artifact@v4
        with:
          name: CountdownTimer-macOS-App
          path: dist/*.app